// examples/svelte-preprocess/src/Count.svelte
<script>
    type CountResult = number
    export let count: CountResult = 5;

    function increment(): void {
        count++;
    }

    function decrement(): void {
        count--;
    }
</script>

<button id="decr" on:click={decrement}>--</button>
<span>{count}</span>
<button id="incr" on:click={increment}>++</button>

// examples/vue/src/Count.vue
<script setup>
import { ref } from 'vue'

const props = defineProps({
  count: { type: Number, default: 5 }
})

const value = ref(props.count)
</script>

<template>
  <button id="decr" @click="value--">--</button>
  <span>{{ value }}</span>
  <button id="incr" @click="value++">++</button>
</template>
