// examples/vue/src/Count.vue
<script setup>
import { ref } from 'vue'

const props = defineProps({
  count: { type: Number, default: 5 }
})

const value = ref(props.count)
</script>

<template>
  <button id="decr" @click="value--">--</button>
  <span>{{ value }}</span>
  <button id="incr" @click="value++">++</button>
</template>

// examples/preact/src/Count.jsx
import { h, Fragment } from 'preact';
import { useState } from 'preact/hooks';

export default function Counter(props) {
	const { count=5 } = props;
	const [value, setValue] = useState(count);

	return (
		<>
			<button id="decr" onClick={() => setValue(value - 1)}>--</button>
			<span>{value}</span>
			<button id="incr" onClick={() => setValue(value + 1)}>++</button>
		</>
	);
}
