// examples/preact/src/Count.jsx
import { h, Fragment } from 'preact';
import { useState } from 'preact/hooks';

export default function Counter(props) {
	const { count=5 } = props;
	const [value, setValue] = useState(count);

	return (
		<>
			<button id="decr" onClick={() => setValue(value - 1)}>--</button>
			<span>{value}</span>
			<button id="incr" onClick={() => setValue(value + 1)}>++</button>
		</>
	);
}

// examples/solidjs/src/Count.tsx
import { createSignal, Component } from 'solid-js'

export type CountProps = { count?: number };

export const Count: Component<CountProps> = (props) => {
	const [value, setValue] = createSignal(props.count ?? 5);

	return <>
		<button onClick={() => setValue(v => v - 1)}>--</button>
		<span>{value()}</span>
		<button onClick={() => setValue(v => v + 1)}>++</button>
	</>
}
